# ======================================================================================
# Project metadata
# ======================================================================================

[project]
name = "test_repo"
description = "this_is_a_test"
version = "0.1.0"
requires-python = ">=3.11"
